dist: xenial
language: bash 
sudo: required
env:

services:
    - docker

# Install dependencies
#before_install:
  #- pip install --upgrade pip
#install:
  #- pip install pytest==3.0.6
  #- pip install -r requirements.txt

# Terraform Plan and Apply
# Plan only on pull requests, Apply on merged code
jobs:
  include:
    - stage: test app
      if: type IN (push) and branch = master
      script:
        - python3 main.py

after_success:
  - sh .travis/deploy_dockerhub.sh
  #- pip install --user awscli
  #- export PATH=$PATH:$HOME/.local/bin
  # Heroku Deployment:
  #- test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh